# Generated by Django 6.0 on 2025-12-24 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
        #migrations.RunSQL("""
        #    INSERT INTO store_collection (title)
        #    VALUES('collection1')
        #""","""
        #    DELETE FROM store_collection
        #    WHERE title='collection1'
        #""")
    ]
